import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { Square, EyeOff, ListTree } from 'lucide-react';
import { getTaskStatusText } from '../../../../../../shared/types';
import { StatusBadge } from './StatusBadge';
import { ProgressBar } from './ProgressBar';
import { formatDuration } from './task-helpers';
export function TaskRow({ task, isSelected, onSelect, onCancel, onHide, onViewData }) {
    const canCancel = task.status === 'queued' || task.status === 'started' || task.status === 'running';
    return (_jsxs("tr", { className: `border-b cursor-pointer transition-colors hover:bg-muted/30 ${isSelected ? 'bg-muted/50' : ''}`, onClick: onSelect, children: [_jsxs("td", { className: "px-4 py-2.5 text-xs font-mono text-muted-foreground", children: [task.taskId.slice(0, 8), "\u2026"] }), _jsx("td", { className: "px-4 py-2.5 text-sm max-w-[160px] truncate", children: task.type || '—' }), _jsx("td", { className: "px-4 py-2.5", children: _jsx(StatusBadge, { status: task.status }) }), _jsx("td", { className: "px-4 py-2.5 text-xs capitalize text-muted-foreground", children: task.priority }), _jsx("td", { className: "px-4 py-2.5", children: _jsxs("div", { className: "space-y-1", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(ProgressBar, { percent: task.progress.percent }), _jsxs("span", { className: "text-xs text-muted-foreground w-8 shrink-0", children: [task.progress.percent, "%"] })] }), _jsx("div", { className: "max-w-[220px] truncate text-[11px] text-muted-foreground", children: task.progress.message || getTaskStatusText(task.metadata) || '—' })] }) }), _jsx("td", { className: "px-4 py-2.5 text-xs text-muted-foreground", children: formatDuration(task.durationMs) }), _jsx("td", { className: "px-4 py-2.5", onClick: (e) => e.stopPropagation(), children: _jsxs("div", { className: "flex items-center gap-1", children: [canCancel && (_jsx("button", { type: "button", title: "Cancel", onClick: onCancel, className: "p-1 rounded hover:bg-destructive/10 hover:text-destructive transition-colors text-muted-foreground", children: _jsx(Square, { className: "h-3.5 w-3.5" }) })), _jsx("button", { type: "button", title: "View data", onClick: onViewData, className: "p-1 rounded hover:bg-accent transition-colors text-muted-foreground", children: _jsx(ListTree, { className: "h-3.5 w-3.5" }) }), _jsx("button", { type: "button", title: "Hide", onClick: onHide, className: "p-1 rounded hover:bg-accent transition-colors text-muted-foreground", children: _jsx(EyeOff, { className: "h-3.5 w-3.5" }) })] }) })] }));
}
