import {
	Bot,
	Code2,
	FileText,
	FolderOpen,
	Home,
	LibraryBig,
	MonitorCog,
	Palette,
	Pencil,
	Plug,
	Radio,
	Settings,
	Sparkles,
	User,
	Briefcase,
} from 'lucide-react';
import type { AppSearchActionDefinition } from './types';

export const APP_SEARCH_RESULTS_PER_SECTION = 6;

export const APP_SEARCH_RESULT_KIND_LABELS = {
	action: 'Action',
	document: 'Document',
	resource: 'Resource',
} as const;

export const APP_SEARCH_ACTIONS: AppSearchActionDefinition[] = [
	{
		id: 'welcome',
		title: 'Open Welcome',
		description: 'Go to the workspace landing page.',
		href: '/',
		icon: FileText,
		meta: 'Route',
	},
	{
		id: 'home',
		title: 'Open Home',
		description: 'Jump to the workspace home screen.',
		href: '/home',
		icon: Home,
		meta: 'Route',
	},
	{
		id: 'assistant',
		title: 'Open Assistant',
		description: 'Chat with the AI assistant.',
		href: '/assistant',
		icon: Sparkles,
		meta: 'Route',
	},
	{
		id: 'resources-content',
		title: 'Open Content',
		description: 'Browse imported documents and manage indexing.',
		href: RESOURCE_SECTIONS.content.route,
		icon: RESOURCE_SECTIONS.content.icon,
		meta: 'Route',
	},
	{
		id: 'resources-files',
		title: 'Open Files',
		description: 'Browse imported files and binary assets.',
		href: RESOURCE_SECTIONS.files.route,
		icon: RESOURCE_SECTIONS.files.icon,
		meta: 'Route',
	},
	{
		id: 'settings-general',
		title: 'Open Settings · General',
		description: 'General app preferences and language.',
		href: '/settings/general',
		icon: Settings,
		meta: 'Settings',
	},
	{
		id: 'settings-account',
		title: 'Open Settings · Account',
		description: 'Manage account profile and credentials.',
		href: '/settings/account',
		icon: User,
		meta: 'Settings',
	},
	{
		id: 'settings-workspace',
		title: 'Open Settings · Workspace',
		description: 'Configure workspace paths and behavior.',
		href: '/settings/workspace',
		icon: Briefcase,
		meta: 'Settings',
	},
	{
		id: 'settings-editor',
		title: 'Open Settings · Editor',
		description: 'Editor appearance, fonts, and behavior.',
		href: '/settings/editor',
		icon: Pencil,
		meta: 'Settings',
	},
	{
		id: 'settings-themes',
		title: 'Open Settings · Themes',
		description: 'Switch theme and accent colors.',
		href: '/settings/themes',
		icon: Palette,
		meta: 'Settings',
	},
	{
		id: 'settings-agents',
		title: 'Open Settings · Agents',
		description: 'Configure AI agents and their tools.',
		href: '/settings/agents',
		icon: Bot,
		meta: 'Settings',
	},
	{
		id: 'settings-providers',
		title: 'Open Settings · Providers',
		description: 'Manage LLM providers and API keys.',
		href: '/settings/providers',
		icon: Plug,
		meta: 'Settings',
	},
	{
		id: 'settings-channels',
		title: 'Open Settings · Channels',
		description: 'Manage delivery channels and integrations.',
		href: '/settings/channels',
		icon: Radio,
		meta: 'Settings',
	},
	{
		id: 'settings-system',
		title: 'Open Settings · System',
		description: 'System-level settings and updates.',
		href: '/settings/system',
		icon: MonitorCog,
		meta: 'Settings',
	},
	{
		id: 'settings-developer',
		title: 'Open Settings · Developer',
		description: 'Developer tools and diagnostics.',
		href: '/settings/developer',
		icon: Code2,
		meta: 'Settings',
	},
];

export const APP_SEARCH_SECTION_ICONS = {
	actions: Home,
	documents: FolderOpen,
	resources: LibraryBig,
} as const;
