import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useCallback, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { SlidersHorizontal, FolderOpen, Sun, Moon } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuLabel, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuTrigger, } from '@/components/ui/DropdownMenu';
import { Slider } from '@/components/ui/Slider';
export default function DocumentSettings({ documentId, }) {
    const { t } = useTranslation();
    const [open, setOpen] = useState(false);
    const handleOpenFolder = useCallback(() => {
        if (!documentId)
            return;
        window.workspace.openDocumentFolder(documentId);
    }, [documentId]);
    return (_jsxs(DropdownMenu, { open: open, onOpenChange: setOpen, children: [_jsx(DropdownMenuTrigger, { render: _jsx(Button, { variant: "ghost", size: "icon", title: t('configSidebar.documentInfo', 'Document info'), "aria-label": t('configSidebar.documentInfo', 'Document info'), children: _jsx(SlidersHorizontal, { "aria-hidden": "true" }) }) }), _jsxs(DropdownMenuContent, { align: "end", className: "w-64", children: [_jsx(DropdownMenuGroup, { children: _jsx(DropdownMenuLabel, { className: "truncate text-sm font-medium text-foreground", children: "Document settings" }) }), _jsx(DropdownMenuSeparator, {}), _jsxs(DropdownMenuGroup, { children: [_jsxs("div", { className: "px-1.5 py-1", children: [_jsx("div", { className: "mb-1.5 flex items-center justify-between", children: _jsx("span", { className: "text-xs font-medium", children: "Width" }) }), _jsx(Slider, { defaultValue: [75], max: 100, step: 1, className: "mx-auto w-full max-w-xs" })] }), _jsxs("div", { className: "px-1.5 py-1", children: [_jsx("div", { className: "mb-1.5 flex items-center justify-between", children: _jsx("span", { className: "text-xs font-medium", children: "Text size" }) }), _jsx(Slider, { defaultValue: [75], max: 100, step: 1, className: "mx-auto w-full max-w-xs" })] })] }), _jsx(DropdownMenuSeparator, {}), _jsxs(DropdownMenuGroup, { children: [_jsx(DropdownMenuLabel, { children: "Font" }), _jsxs(DropdownMenuRadioGroup, { defaultValue: "sans", children: [_jsx(DropdownMenuRadioItem, { value: "sans", children: _jsx("span", { className: "font-sans", children: "Sans" }) }), _jsx(DropdownMenuRadioItem, { value: "serif", children: _jsx("span", { className: "font-serif", children: "Serif" }) }), _jsx(DropdownMenuRadioItem, { value: "mono", children: _jsx("span", { className: "font-mono", children: "Mono" }) })] })] }), _jsx(DropdownMenuSeparator, {}), _jsxs(DropdownMenuGroup, { children: [_jsx(DropdownMenuLabel, { children: "Theme" }), _jsxs(DropdownMenuRadioGroup, { defaultValue: "light", children: [_jsxs(DropdownMenuRadioItem, { value: "light", children: [_jsx(Sun, { className: "text-muted-foreground", "aria-hidden": "true" }), _jsx("span", { children: "Light" })] }), _jsxs(DropdownMenuRadioItem, { value: "dark", children: [_jsx(Moon, { className: "text-muted-foreground", "aria-hidden": "true" }), _jsx("span", { children: "Dark" })] })] })] }), _jsx(DropdownMenuSeparator, {}), _jsx(DropdownMenuGroup, { children: _jsxs(DropdownMenuItem, { onClick: handleOpenFolder, disabled: !documentId, children: [_jsx(FolderOpen, { className: "text-muted-foreground", "aria-hidden": "true" }), _jsx("span", { className: "truncate", children: t('configSidebar.openFolder', 'Open folder') })] }) })] })] }));
}
